@include('Admin/layouts/header')
@include('Admin/layouts/mainheader')
    @include('Admin/layouts/leftsidebar')
    @include('Admin/layouts/Countries/viewCreateCity') 
@include('Admin/layouts/footer')
