@include('Admin/layouts/header')
@include('Admin/layouts/mainheader')
@include('Admin/layouts/leftsidebar')
    @include('Admin/layouts/Property/sub_viewCreateProperty') 
@include('Admin/layouts/footer')
