@include('Admin/layouts/header')
@include('Admin/layouts/mainheader')
@include('Admin/layouts/leftsidebar')
    @include('Admin/layouts/Categories/viewCreateCategory') 
@include('Admin/layouts/footer')
