@include('Admin/layouts/header')
@include('Admin/layouts/mainheader')
@include('Admin/layouts/leftsidebar')
    @include('Admin/layouts/Question/viewCreateQuestion') 
@include('Admin/layouts/footer')
